[package]
name = "rs_chip8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.21.3"
typenum = "1.15.0"
ggez = "0.7.0"
rand = "0.8.5"